language: python
python:
- '3.7'
install:
- pip install -r requirements.txt coverage coveralls pytest-cov
script:
- python -m pytest --cov=quickanalysis tests
after_success: coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "us-east-1"
  app: "quickanalysis"
  env: "quickanalysis-dev"
  bucket_name: "quickanalysis-bucket"
  on:
    branch: main

env:
  global:
  - secure: SE9JthzhCn1xGIyhfvl/fJ5Y6IB9mEGY9g8gswRmZlsi/JWFC7qpAy/qgh9cWNvGx1ZMS8NrzwJ4twXEPDzuKrE4h4CXFvmqDqFCXkZQf5VdOOSQNP9gkbUSJ8Pwj6PCcE7BDY/dw/Mu3t7ZoS8IIGC5NQ9fPwG/0EE+scog41kSQifQPy1Izi1y7wpAcWR6K+Zb9ZDdsNr0jeNQwwBKyIRBAHDUBB9pn9V/aoXhlBVTjpZsgyKq2P/JNJhH99HCC1YfyYqVQn6moTXVj2qJmwqXvYL5YSLEClw0kPSeG+1X/4LtJRVKuOl9cVlaJEuQ9EXN1LQK/ew0oIJT68rHw9MA3bA4o0fNJmyqm5XNDNOQXskYgfXeXb21X+4SdF8jN1h1FJZeLZjj9jyUiaoma8svpJw1aFbNC+P8pbGSLeZSOVazP5eRjLWzodDS0x+NCe2sgWTPU44avrgCcot3yG9whEWjDsRrXx0pQ2UJdpZB1n+SMF0GTQwKgMlhd6JgFeJxndp6JuIh5iFVEovzYGePcz55TLiewI9K8+sPHIgw1NVoX2QJuX5MhNHnsyzPN5o/fWcidH+I+i/jWq1PJzDOatceV4dbQYMFVd5LiCBwHkWD7rV0eDrp6f6cCu/BlaMukiOjOM82wv7FLQy0OsLfa0ZieqNfZeroWJjSwMI=
  - secure: dwPxtyTISQn0BBh+xRp54SbRH3xR6kfxyLWtTGywgiuzYwJ8POMQkvLlFi/0VqAyGYlZgUQGx8FmvxKQNKr8f02q3lw1UOD7UdWd2I8jOEsBa9Z98ZAF5uN5NY1x6OO64/8IbEToRO0I8wXu2qmDEn0EC4IiwOWBu3syztJ/XVcycnRhAytKAiNeJaM4wBgEwpLZoFeuZ1ud6h2EaWUzM6ishSAf0h28gcTQAoYnI9+aCWB++kdyqOKPiENXW8YikJGSnvyuRavjRfknABdY/EBDk3+IOEt+l2/OjR/7aQn8Z+D1Zb2sI+UXZF46VhuyDnWk3WtqaVYCirJ0dLcYTw42pKYnRZRV+kkIg5LguHluB6IRnEH08HEhxQpIMPDg1QXirfzBUmFgQMjqdtJ4u9fqiWe8mzW2pFw4RD8cuD/Y80IsaPor5uFLOaZa8yJRH6j3CX0iTkylU2ams4eH30AWiypcxpOQIsvpCxiPUaH6RG7nGARnq+4wvDNnxQy9LSsKGs7iimNXfUKGI2wKZCFUmk3bUPEtCLjlshWTNrApZKsu3biyOC/G26Dc98jlnHJ9/p+jral20qW8uu0oRbqx87O2H0HtAfpdIB1FFec0QSaK6ouSEsubtdEuyFLesFlFtdWvnCOwhvvBJbYA4b90ZLbr8UmwGLjFNOzlTTI=
